### ISSUE TITLE
Consider how to allow arbitrary config options to be passed to the producer / consumer

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-kafka#12]
Option 1. I think since we're fixed on certain producer / consumer versions, we can just use an opts map (potentially blacklisting some options that we allow).

Option 2. Another option is to inject a producer/consumer, but this could get messy to support, and is still kinda cumbersome for users.

Option 3. Last option is to just code up an arbitrary rule to convert the parameter styles and support all config options. This doesn't future proof us very well and requires us to document everything.

I prefer 3 or 1 vastly more than 2.

**Comment by MichaelDrogalis** [comment]
I'm not sure if this is what you mean by option 3, but here's what I've come up with:

Continue to support the options that we do now, prefixed with `:kafka/`. For all other keys, we allow `:kafka*/`. We take all keys that are prefixed with `:kafka*/`, remove that prefix, and take the suffix as-is, merging it last into the parameters map. This retains the flat-map style of the catalog, keeps the options we already support, and allows the escape hatch we're looking for.

**Comment by lbradstreet** [comment]
That's pretty close to what I was suggesting with 3, although I was going to force the options to be configured and documented.

**Comment by MichaelDrogalis** [comment]
Wouldn't that get in the way out allowing arbitrary configuration keys for the underlying producer/consumer that we haven't thought of? I'm probably misunderstanding.

**Comment by lbradstreet** [comment]
Yeah, that would probably get in the way of any new keys that they might
add, though it would allow us to document them in the README rather than
just defining a conversion scheme. Anyway, I like your idea. Let's check
whether we can str every kafka config option before passing it on,
considering that parse issue that popped up the other day.

**Comment by lbradstreet** [comment]
Closed as this is in master.
