### ISSUE TITLE
:onyx/min-peers must equal :onyx/max-peers error when using :onyx/n-peers

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx-kafka#24]
It's my understanding from the cheatsheet that given that `:onyx/n-peers` is

> A convenience parameter which expands to :onyx/min-peers and :onyx/max-peers set to the same value

that it should cause this error to happen if it's used.

**Comment by MichaelDrogalis** [comment]
@neverfox What error exactly are you seeing? `:onyx/n-peers` and min/max are mutually exclusive, I think the docs may need to clarify that.

**Comment by neverfox** [comment]
Sorry for being unclear. I mean that I'm wanting to use n-peers as an alternative to min/max-peers, but the kafka plugin [only checks min and/or max-peers](https://github.com/onyx-platform/onyx-kafka/blob/kafka-0.9/src/onyx/plugin/kafka.clj#L172) when doing the partition verification, so it throws the ":onyx/min-peers must equal :onyx/max-peers and the number of kafka partitions" exception, because they're both nil. I believe it should check for n-peers also before assuming that the condition doesn't hold.

**Comment by lbradstreet** [comment]
Yep, that is definitely a bug then. Thanks.

**Comment by lbradstreet** [comment]
Fixed in https://github.com/onyx-platform/onyx-kafka/commit/57b9a081596f95a7b0dfc9f4edacf6d253de37b9

**Comment by lbradstreet** [comment]
Thanks for the report.
