### ISSUE TITLE
Only restart jobs that are likely to succeed

### ISSUE THREAD

**Issue by jcf** [onyx-platform/onyx-kafka#28]
Moved over from: https://github.com/onyx-platform/onyx/issues/635

When I start my system I encounter an error because something is misconfigured. When the task can't be started it gets restarted again and again only to fail over and over.

```
clojure.lang.ExceptionInfo: Caught exception inside task lifecycle. Rebooting the task. -> Exception type: clojure.lang.ExceptionInfo. Exception message: :onyx/min-peers must equal :onyx/max-peers and the number of partitions, or :onyx/n-peers must equal number of kafka partitions
```

This fills up my logs, and doesn't really help me solve the underlying issue.

**Comment by jcf** [comment]
Thanks, @lbradstreet!

**Comment by lbradstreet** [comment]
Closing. Tracking on onyx#635

**Comment by lbradstreet** [comment]
Sorry, had that the wrong way around!

**Comment by lbradstreet** [comment]
onyx-kafka no longer restarts on several common exception types
