### ISSUE TITLE
Keyed messages support

### ISSUE THREAD

**Issue by lgrapenthin** [onyx-platform/onyx-kafka#3]
Learning about Kafka I realized that I could have use for keyed messages in combination with log compaction. It made me wonder whether it is planned to support keyed messages in this plugin and how straightforward the necessary changes would be, i. e. would adding and implementing a parameter for key serialization/deserialization suffice?

**Comment by MichaelDrogalis** [comment]
Hi @lgrapenthin,

I don't use Kafka on a day-to-day basis, so I'm not familiar with the most recent features that have come out. It seems like you could add either add a `:write-keyed-messages` which alters [this line](https://github.com/onyx-platform/onyx-kafka/blob/0.6.x/src/onyx/plugin/kafka.clj#L192), or supply a catalog parameter like `:kafka/keyed?`. Doesn't seem like it would be too bad.

**Comment by lbradstreet** [comment]
This should be easy to implement, but there are a few ways to go.

Option 1: Switch the kafka output plugin take segments in the form:
`{:key somekey :message somemessaage}`

If a segment has a `:key` key, then we write it with a key, if not we write it without. Switching the output plugin to this format is a big advantage if we ever want to add other message related options to the output plugin.

Option 2: Add `:kafka/keyed?` to the task map and require it to be in that form when it is used.

Option 3: Add `:kafka/key`, which, when supplied pulls the key out of the segment.

Out of the three options, I much prefer option 1. It's the cleanest (doesn't mix kafka related properties with the segment which is your data), and it has the most flexibility in the future.

**Comment by MichaelDrogalis** [comment]
Number 1 is good to me, it's similar to how the Datomic plugin provides bulk transaction writing.

**Comment by lbradstreet** [comment]
Implemented in #5

**Comment by MichaelDrogalis** [comment]
Well done! Merged!

**Comment by twashing** [comment]
@lbradstreet Thanks for writing this feature. I'm keen to be able to read in, as well as write out kafka message keys. But I only see an interface to be able to write out message keys (see [here](https://github.com/onyx-platform/onyx-kafka#write-messages)). How can we pull in kafka message keys, in our code. I don't see an example of this in the [test suite](https://github.com/onyx-platform/onyx-kafka/tree/0.10.x/test/onyx/plugin).

Looks like if we set `:kafka/wrap-with-metadata?` to true, we'll be able to pull in kafka message keys, along with the message (see [here](https://github.com/onyx-platform/onyx-kafka/blob/0.10.x/src/onyx/plugin/kafka.clj#L207)). 

I'm looking at this `segment-fn` code, which indeed pulls in the message key. That is part of the `onyx.plugin.kafka.read-messages` function, which should return a `onyx.plugin.kafka.KafkaReadMessages` deftype (see [here](https://github.com/onyx-platform/onyx-kafka/blob/0.10.x/src/onyx/plugin/kafka.clj#L209-L215)). 

That `onyx.plugin.kafka.KafkaReadMessages` deftype has a `poll` function attached, which looks like it pulls out a batch of `org.apache.kafka.clients.consumer.ConsumerRecords`.Where in onyx-kafka's lifecycle, can user-land workflow code pull in those `ConsumerRecords`, or just the kafka message and key?

**Comment by lbradstreet** [comment]
@twashing if you use a snapshot build of onyx-kafka, we now support this via wrap-with-metadata?. You can try it out with version `0.10.0.0-20170507.050320-44`.

See https://github.com/onyx-platform/onyx-kafka/blob/master/src/onyx/plugin/kafka.clj#L212 for what is now included in wrap-with-metadata?.

Let us know if you hit any problems!

**Comment by twashing** [comment]
@lbradstreet Got it. So in your ` :onyx/fn`, the segment will be the message with all the extra stuff. Not just the byte stream. 
```
{:topic "my-topic", :partition 0, :key #object[...], :message {:foo :bar}, :offset 2}
```

I see that working for me. Cheers.

**Comment by MichaelDrogalis** [comment]
You can optionally provide a `:kafka/key-deserializer-fn` (and for output, `:kafka/key-serializer-fn`) to get back the deserialized key instead of a byte array.

**Comment by twashing** [comment]
Ah ha. That sounds handy. 👍

**Comment by twashing** [comment]
Hey @MichaelDrogalis . So I looked for `:kafka/key-deserializer-fn`, and didn't see it anywhere in the onyx-kafka codebase. This is in the **onyx-kafka** directory.

```
$ date
Mon May  8 11:48:40 PDT 2017

$ git status
On branch 0.10.x
Your branch is up-to-date with 'origin/0.10.x'.
nothing to commit, working directory clean

$ git grep key-deserializer-fn  # empty results
$ ag key-deserializer-fn  # empty results
```

So when I try to add a `:kafka/key-serializer-fn` key to an element in my `catalog`, I get what looks like a schema error. Is the feature maybe in an unpushed development branch? 

```
clojure.lang.ExceptionInfo: Unfreezable type: class clojure.lang.ExceptionInfo
    as-str: "#error {\n :cause \"Unfreezable type: class clojure.lang.ExceptionInfo\"\n :data {:type clojure.lang.ExceptionInfo, :as-str \"#error {\\n :cause \\\"Unfreezable type: class clojure.lang.ExceptionInfo\\\"\\n :data {:type clojure.lang.ExceptionInfo, :as-str \\\"#error {\\\\n :cause \\\\\\\"Unfreezable type: class clojure.lang.ExceptionInfo\\\\\\\"\\\\n :data {:type clojure.lang.ExceptionInfo, :as-str \\\\\\\"#error {\\\\\\\\n :cause \\\\\\\\\\\\\\\"Value does not match schema: {(not (= (name (:kafka)) (namespace a-clojure.lang.Keyword))) invalid-key}\\\\\\\\\\\\\\\"\\\\\\\\n :data {:type :schema.core/error, :schema {#schema.core.OptionalKey{:k :kafka/topic} java.lang.String, :kafka/zookeeper java.lang.String, :kafka/serializer-fn (pred keyword-namespaced?), #schema.core.OptionalKey{:k :kafka/request-size} java.lang.Number, #schema.core.OptionalKey{:k :kafka/partition} (cond-pre Int Str), #schema.core.OptionalKey{:k :kafka/no-seal?} java.lang.Boolean, #schema.core.OptionalKey{:k :kafka/producer-opts} {Any Any}, [:restricted-ns (:kafka)] Any}, :value {:kafka/zookeeper \\\\\\\\\\\\\\\"zookeeper:2181\\\\\\\\\\\\\\\", :kafka/key-serializer-fn :com.interrupt.streaming.platform/serialize-kafka-key, :onyx/plugin :onyx.plugin.kafka/write-messages, :onyx/medium :kafka, :kafka/request-size 307200, :onyx/type :output, :onyx/name :scanner, :kafka/topic \\\\\\\\\\\\\\\"scanner\\\\\\\\\\\\\\\", :kafka/serializer-fn :com.interrupt.streaming.platform/serialize-kafka-message, :onyx/max-peers 1, :onyx/min-peers 1, :onyx/doc \\\\\\\\\\\\\\\"Writes messages to a Kafka topic\\\\\\\\\\\\\\\", :onyx/batch-size 10}, :error {(not (= (name (:kafka)) (namespace a-clojure.lang.Keyword))) invalid-key}, :original-exception :clojure.lang.ExceptionInfo}\\\\\\\\n :via\\\\\\\\n [{:type clojure.lang.ExceptionInfo\\\\\\\\n   :message \\\\\\\\\\\\\\\"Value does not match schema: {(not (= (name (:kafka)) (namespace a-clojure.lang.Keyword))) invalid-key}\\\\\\\\\\\\\\\"\\\\\\\\n   :data {:type :schema.core/error, :schema {#schema.core.OptionalKey{:k :kafka/topic} java.lang.String, :kafka/zookeeper java.lang.String, :kafka/serializer-fn (pred keyword-namespaced?), #schema.core.OptionalKey{:k :kafka/request-size} java.lang.Number, #schema.core.OptionalKey{:k :kafka/partition} (cond-pre Int Str), #schema.core.OptionalKey
```

**Comment by MichaelDrogalis** [comment]
Switch to the master branch - we haven't released it yet in non-snapshot form. You can get it with `0.10.0.0-20170507.050320-44`.

**Comment by twashing** [comment]
Et voila!! Merci @MichaelDrogalis :)
