### ISSUE TITLE
Need a throughput / latency test

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-kafka#30]
We need performance tests for the plugins, not just onyx core. onyx-kafka would be the best place to start.

Initially it would be fine to run the test with an embedded broker, on a single machine. A test to detect the most egregious problems would be enough initially.

**Comment by ducky427** [comment]
@lbradstreet, I've created a test [here](https://github.com/ducky427/onyx-kafka-sample). This is representative of the workload I am working with.

**Comment by lbradstreet** [comment]
Much appreciated. I have also created on on another branch, but I will incorporate the characteristics of your test into it. 

Cheers

Lucas

**Comment by lbradstreet** [comment]
Have a throughput test now. We still need a producer test. Closing this item and re-opening a producer test item
