### ISSUE TITLE
fixed-partition only supports setting max-peers, not n-peers

### ISSUE THREAD

**Issue by aaron-daly** [onyx-platform/onyx-kafka#31]
When using a fixed partition for a consumer, 'fixed-partition?' on line 128 of kafka.clj only checks if (= 1 max-peers). Shouldn't this also check for (= 1 n-peers)?

**Comment by MichaelDrogalis** [comment]
cc @lbradstreet

**Comment by lbradstreet** [comment]
Fixed 6a049295e101a44171e9146edf55facb70cbe0b6
