### ISSUE TITLE
NPE caused by missing either :onyx/n-peers or :onyx/max-peers

### ISSUE THREAD

**Issue by kennyjwilli** [onyx-platform/onyx-kafka#49]
I think the docs on onyx-kafka should mention which keys are required. I just ran into a NPE due to not having set `:onyx/n-peers` or `:onyx/max-peers` caused by: https://github.com/onyx-platform/onyx-kafka/blob/86f422389d32d9feb526355954ec4ffa08638df5/src/onyx/plugin/kafka.clj#L80 

It would've been helpful to have known I need to specify one of those.

**Comment by lbradstreet** [comment]
Fixed in master. The problem was in the condition that checked whether min-peers = max-peers, as both were nil, and it was allowed rather than specifying that one must be set.
