### ISSUE TITLE
Add schema checks of task-maps

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-kafka#8]
The task map entries are getting more complicated over time, and we're having to add validation for kvs that are changing between versions. We should add a schema check for task maps entries to make this process easier.

Schema checks should be relatively non-strict, i.e. they only check the keys and values that are known about by the plugin, and ignore any additional keys.

**Comment by gardnervickers** [comment]
I believe this is solved with task bundle schemas.

**Comment by lbradstreet** [comment]
Task bundles are added now.

**Comment by lbradstreet** [comment]
This is still relevant as not all users will be using task bundles. Leaving open for now, but it is not currently a priority until ABS is here and we redo onyx-kafka.

**Comment by lbradstreet** [comment]
Done in master.
